# Generated by Django 3.1.6 on 2021-03-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0003_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
    ]
